### ISSUE TITLE
所以就來幫 HTML 化妝吧......

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Sara#12]
好的，既然你在 #11 打算把 CSS 的部份混過去（謎之聲：阿 CSS 就不是主題阿），那當然就讓你 ~~像楊露禪手中的麻雀一樣無處借力~~ 無處可逃。

CSS / HTML 對於程式設計師來說，就很像 M$ Word 對於大學生，沒有一堂課在教這玩意，但是每個教授都覺得你會用、所以指定用他來交報告（至少我念大學的時候是這樣 XD）。而 CSS 也的確很像（我印象中的） M$ Word，乍看之下好像很簡單，但是當你真真正正要弄出你理想中的樣子，不是各種爆炸就是各種硬幹補漏洞...... 🤢 

anyway... 這個 issue 只打算進行基本的部份（謎之聲：我不相信），因為進階的我也不會（謎之聲：我可以相信）。所以看到下列主題的 reference 請完全跳過：

* 牽扯到 JavaScript 的部份
* 牽扯到 CSSOM 的部份
* cross browser 的議題（所以只要 Chrome 上頭正常即可）
* SASS / GSS...... 等 CSS 變體
    * 光叫 GSS 的就有兩種...... [扶額]

這個 issue 同時包含了 paper work 跟 presentation。一樣也是 paper work 的 PR accept 之後才會開始進行 presentation 的環節。

-----------

# presentation #
請介紹 CSS 是什麼，包含：

* CSS 要解決什麼事情？
* CSS 語法的設計概念。
    * 這個可能有 87% 機率無法直接狗到 reference（懶得去狗看看，講錯就算了），如果你完全毫無頭緒，至少講清楚在 HTML 當中使用 CSS 的三種方式。
* (option) CSS3 做了哪些補強
* (option) **你覺得** CSS 有什麼問題
    * 因為是 **你覺得**，所以符不符合教科書上的學術理論不重要，只要你沒搞錯對象 / 意思即可

------------

# paper work #

請製造出 **一個** HTML 檔案，裡頭放 `table`（含 `tr`、`td`，其他 t 字輩的就免了），其中一個是用 HTML5 已經不支援的 attribute 製作而成，包含：

* align
* bgColor
* cellPadding
* cellSpacing

另外一個 table 是用 CSS 取代上述 attribute 但是做出視覺上一模一樣效果。

請注意：

* 請製造出可以明顯看出上述 attribute 功效的 case
* 上述 attribute 不一定都用在 `table` 上，有些也可以用在 `tr` / `td` 上頭
* 不是只能用 `table` / `tr` / `td`，其他 HTML tag 你覺得有需要都可以拿來用
* CSS 請用 embedded 方式，並且只能用 class 的 selector

檔案的名稱與路徑是 `/docs/table.html`

----------------------------

最後再提醒一次，每次 PR accept 之後請務必按照 FlowTraining Task2 的方式操作你的 local repo，然後再從 `master` branch 開新的 branch。

**Comment by SayHello123** [comment]
> 最後再提醒一次，每次 PR accept 之後請務必按照 FlowTraining Task2 的方式操作你的 local repo，然後再從 master branch 開新的 branch。

請問我需要等 issue 6 收到 PR accept 結束後才能用使用 `git pull -r `  嗎？

**Comment by MontyPan** [comment]
=.= 用 git 的重點就是：如果 issue 之間是獨立的，那麼 git 操作也不會互相影響。

所以，簡單的答案就是：不用。

複雜的答案是：因為你之前都沒做過，所以現在你要開新的 branch 之前得作。

**Comment by MontyPan** [comment]
這邊補充一下 https://github.com/MontyPan/T-Sara/pull/14#issuecomment-656557030 的哏。

你原本的寫法就會對的原因，（理論上）是因為「element 的大小未必一定要由 CSS 或是傳統 attribute 指定，在預設 or 特定情況下，本身就可以自己決定大小（通常是由 child element / context 決定）」。

這個特性蠻重要、蠻好用、也蠻惱人的，**如果要精通基礎 CSS** （精通？基礎？）的話，boxing model 跟什們其況下 element 會有這個特性（也許算在 boxing model 範圍內？）是首要大重點，因為沒搞懂這個就沒辦法處理 position、沒辦法處理 position 那還排版排個雕.........

先說我沒有認真去確認你的 case 是不是真的是因為這個特性而能正常顯示，就如同我一直強調的，其實 CSS 我根本不熟...... [光速逃]

看完之後請自己關掉這個 issue（如果你沒有權限的話，那留個 comment 吧....）
