### ISSUE TITLE
等等等等等等... 等差數列！

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Sara#15]
~~標題哏不懂的話請看 STR Network 的 《Taiwan》~~

# 程式部份 #

請寫出一個程式，可以在螢幕上印出指定條件下的等差數列以及其級數形式的合。

`main()` （的開頭）大概會長這樣：

```Java
public static void main(String[] args) {
    int a1 = 1;  //首項
    int d = 2;  //公差
    int n = 5;  //項數
    //上面這三個變數值可以（合理地）改變，而程式結果也要能正確對應

}
```

在 (a1, d, n) 是 (1, 2, 5)（也就是上面程式的變數設定）的狀況下，程式輸出應該會是：

```
1, 3, 5, 7, 9
25
```

然後：

* 你要加一些無傷大雅的提示字串 / title 是允許的
* 你可以不用考慮到螢幕 / console 寬度而導致的換行閱讀問題
    * 當然如果你堅持要考慮的話，可以假設螢幕寬度只能容納 80 個半形字元。（謎之聲：我才不會堅持這玩意）（也好，因為那個要寫起來還蠻麻煩的）
* 對，沒錯，不需要任何新的語法，你也不能用任何新的語法（包括字串相加）
    * 請注意 `System.out.print()` 跟 `System.out.println()` 的差別。

# 數學部份 #

請（用數學方式 & 數學詞彙）證明如果 a1 跟 d 都是整數（n 一定得是整數），則其等差級數的和也必然是整數。

請直接在這個 issue 的 comment 回答（對，**不要** 在 PR 那裡回答，所以你可以先回答這題）。

**Comment by SayHello123** [comment]
因等差數列的公差一定為後一項減前一項，所以如果首項為整數，公差就一定是整數；而因為首項與公差為整數，則等差數列求的和必為整數。
整數包含：負整數、零、正整數

證明：

求 1, 3, 5, 7, 9 之和，n 為 2
Sn = (1+9) * 5 * 1/2 
Sn = 25

求 -2, 0, 2, 4, 6, 8 ,10之和，n 為 2
Sn = (-2+10) * 7 * 1/2
Sn = 28

求 -10, -8, -6, -4, -2, 0 之和，n 為 2
Sn = (-10+0) * 6 * 1/2
Sn = -30

求10, 7, 4, 1, -2, -5, -8, -11 之和，n 為 -3
Sn = (10+(-11)) * 8 * 1/2
Sn = -4

**Comment by MontyPan** [comment]
滿滿的吐槽點阿....

> 因等差數列的公差一定為後一項減前一項

這不叫做「一定」，這叫做「定義」

> 所以如果首項為整數，公差就一定是整數

數學的美妙之處之一，就是如果要要證明一個敘述有錯很簡單，找出一個反例就好，我就大發慈悲給你一個反例：

1, 0.9, 0.8, 0.7, 0.6

請問這是不是等差數列？請問 a1 是不是整數？請問 d 是整數嗎？

然後，基本上你的敘述似乎是在... 證明（？）前提假設？前提假設是拿來用的，是你的武器而不是你要打倒的敵人。

然後，我們用 a1 / d / n 這三個數值來描述一個等差數列是有其道理的，因為這三個數值就能描述所有的等差數列，而且不會產生任何模糊不清的可能。

最後，你根本沒有證明，那句「因為首項與公差為整數，則等差數列求的和必為整數。」只是加強語氣的方式複誦題目，而你下面洋洋灑灑的「證明」，抱歉，那不叫證明，那叫舉例。

數學的另一個美妙之處，就是你不能用舉例的方法來證明某一個公式 / 定理 / 數學敘述是對的，除非你能舉完所有的例子（aka 窮舉）。

很抱歉，你沒有窮舉，事實上，（數學會告訴你）你也無法窮舉。

---------

看起來要你用數學的方式真的是很難的事情（因為你連敵人 / 目標是誰都搞錯.... ），我就幫你縮限一下題目好了 [扶額]

你在 ~~不是證明的~~ 證明區裡頭用了求和公式，也就是 `(a1 + an) * n / 2`。ㄟ都... 奇怪了... 明明有個除以 2 的動作，要是 `(a1 + an) * n` 是奇數，得到的數字就不會是整數了阿？為什麼 `(a1 + an) * n` 一定會是偶數咧？

寫到這，我發現我題目出得不夠嚴謹，所以補個「n 必須大於等於 2」這個前提，也就是說「如果一個等差數列的 a1, d 是整數，n 又大於 1 的情況下，其級數和也必然是整數」。這... 也算提示吧..... [慘笑]

**Comment by SayHello123** [comment]
1, 4, 7, 10
Sn = (1+10) * 4 / 2 = 22
若 a1 為奇數、d 為奇數、n 為偶數，則 an 就會是偶數
1, 3, 5, 7, 9
Sn = (1+9) * 5 / 2 = 25
若 a1 為奇數、d 為偶數、n 為奇數，則 an 就會是奇數

結論；
因為奇數或偶數乘以偶數和奇數相乘都會是偶數，所以只要 n 或 `(a1 + an)` 其中一個為偶數，或是 n 和 `(a1 + an)` 皆為奇數，`(a1 + an) * n` 就一定會是整數（n 大於 1 的前提下）

**Comment by MontyPan** [comment]
＝＝"

* 請不要再舉實際例子，舉再多都沒有用的，那是證明錯誤的時候才會考慮的事情。
* 「若 a1 為奇數、d 為奇數、n 為偶數，則 an 就會是偶數」這是數學敘述沒錯（傳說中的「若 A 則 B」句型），但是我看不出來 A 要怎麼推導到 B（就算是上頭那個舉例也沒用）
* 你要用這個路線去證明（當然，你得先解決上一點的證明），雖然很 low，但抓得到老鼠的就是好貓，所以也不能認真吐槽（反正寫的不是我...... 😴 ）。但就算你解決上一點的證明，也還是少了很多東西，無法認為你已經證明完。
    * 就是因為用這個路線得寫很多東西，所以才很 low，數學家（程式設計師基本上也是）喜歡簡單幾個字就解決問題。

**Comment by SayHello123** [comment]
> * 「若 a1 為奇數、d 為奇數、n 為偶數，則 an 就會是偶數」這是數學敘述沒錯（傳說中的「若 A 則 B」句型），但是我看不出來 A 要怎麼推導到 B（就算是上頭那個舉例也沒用）

an = a1 + (n-1)d

> * 你要用這個路線去證明（當然，你得先解決上一點的證明），雖然很 low，但抓得到老鼠的就是好貓，所以也不能認真吐槽（反正寫的不是我...... 😴 ）。但就算你解決上一點的證明，也還是少了很多東西，無法認為你已經證明完。
>   
>   * 就是因為用這個路線得寫很多東西，所以才很 low，數學家（程式設計師基本上也是）喜歡簡單幾個字就解決問題。

a1、d、n 都為整數（且 n 大於 1），而奇數相乘或奇偶數乘以偶數都會是偶數，所以 `(a1 + an) * n`  必為偶數，因此 `(a1 + an) * n / 2` 就必為整數

**Comment by MontyPan** [comment]
你用這種 quote 回覆有什麼意義？你要交的是一整個證明，單純講出 an = a1 + (n - 1)d 並不能代表什麼，最多也只能說「恩對，a1, d 是 odd、n 是 even，an 的確會是 even」，然後呢？這個證明成立的敘述對你的目標有什麼幫助嗎？**連你最後一直掛在嘴邊的「(a1 + an) * n 必為偶數」都證明不了**

然後，上次懶得仔細看，所以沒發現 or 特地拿出來講，這次你八成又複製貼上所以我不挑出來不行

* 沒有「奇偶數」這種東西，你至少也講「奇數或偶數」或是乾脆直接講「任何整數」
* 兩個 odd 相乘是要怎麼算才會得到偶數？ 😱

**Comment by SayHello123** [comment]
> 你用這種 quote 回覆有什麼意義？你要交的是一整個證明，單純講出 an = a1 + (n - 1)d 並不能代表什麼，最多也只能說「恩對，a1, d 是 odd、n 是 even，an 的確會是 even」，然後呢？這個證明成立的敘述對你的目標有什麼幫助嗎？**連你最後一直掛在嘴邊的「(a1 + an) * n 必為偶數」都證明不了**
> 
> 然後，上次懶得仔細看，所以沒發現 or 特地拿出來講，這次你八成又複製貼上所以我不挑出來不行

沒有複製貼上，如有雷同，實屬巧合
> 
> * 沒有「奇偶數」這種東西，你至少也講「奇數或偶數」或是乾脆直接講「任何整數」

好奇餵狗查了一下資料，有「奇偶數」，但比較多的是「奇偶性」，不過確實不是「奇數或偶數」的意思

-----------------------------------------------
### 如果 a1 跟 d 都是整數（n 一定得是整數且 >= 2），則其等差級數的和也必然是整數

若 d 為偶數，則 (a1+an) 必為偶數，所以  (a1+an) * n 必為偶數，而 (a1+an) * n / 2 也將必為整數。
若 d 為奇數，當 (a1+an) 為奇數時，n 必為偶數；而當 (a1+an) 為偶數時，n 必為奇數，而兩種結果相乘都會是偶數，所以 (a1+an) * n / 2 也將必為整數。

**Comment by MontyPan** [comment]
「若 A 則必為 XX」都需要推導，不然你乾脆直接照抄題目就可以當答案了。

**Comment by SayHello123** [comment]
> ### 如果 a1 跟 d 都是整數（n 一定得是整數且 >= 2），則其等差級數的和也必然是整數
> 若 d 為偶數，則 `(a1+an)` 必為偶數，所以 `(a1+an) * n` 必為偶數，而 `(a1+an) * n / 2` 也將必為整數。

若 d 為偶數，當 a1 為奇數時，an 必為奇數，奇數相加後為偶數；而當 a1 為偶數時，an 必為偶數，偶數相加後為偶數，所以當 d 為偶數時，`(a1+an) * n / 2` 將必為整數。

> 若 d 為奇數，當 `(a1+an)` 為奇數時，n 必為偶數；而當 `(a1+an)` 為偶數時，n 必為奇數，而兩種結果相乘都會是偶數，所以 `(a1+an) * n / 2` 也將必為整數。

**Comment by MontyPan** [comment]
我前前一個 comment 也說了，你要交的是一整個證明，不是這種縫縫補補的東西。

我前一個 comment 已經說了，你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

這邊我剛好很幸運（俗話說的撿到槍），因為你如果很嚴謹地寫出所有的「若 A 則必為 B」的憑據，你就會發現你的證明路線根本不用寫那麼多字。

好，你膩了沒我是不知道，因為我看膩了，所以我直接給你個超明確提示（列祖列宗請原諒我這麼做  🙊 ）

# 根本不用管 a1 是 odd 還是 even #

**Comment by SayHello123** [comment]
若 d 為偶數，則 `(a1+an)` 必為偶數，所以 `(a1+an) * n / 2` 將必為整數。

若 d 為奇數，則 `(a1+an)` 與 n 兩者其一必為偶數，所以 `(a1+an) * n / 2` 也將必為整數。

**Comment by SayHello123** [comment]
若 d 為偶數，則 `(a1+an)` 必為偶數，所以 `(a1+an) * n / 2` 將必為整數。

若 d 為奇數，則 `(a1+an)` 與 n 兩者其一必為偶數，所以 `(a1+an) * n / 2` 也將必為整數。

**Comment by MontyPan** [comment]
我前一個 comment 已經說了，你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

我前一個 comment 已經說了，你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

我前一個 comment 已經說了，你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

我前一個 comment 已經說了，你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

我前一個 comment 已經說了，你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

我前一個 comment 已經說了，你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

**Comment by SayHello123** [comment]
若 d 為偶數，則`(a1+an)` 會是奇數相加或是偶數相加，其相加結果都會是偶數，所以 `(a1+an) * n` 必為偶數。

若 d 為奇數，當 n 為偶數時，`(a1+an)` 會是奇數與偶數相加；當 n 為奇數時，`(a1+an)` 會是奇數相加或奇數與偶數相加，所以 `(a1+an) * n`  必為偶數。

因此當 a1、d、n 都為整數（且 n 大於 1）時，`(a1 + an) * n / 2` 就必為整數。

**Comment by MontyPan** [comment]
「則 (a1+an) 會是奇數相加或是偶數相加」、「(a1+an) 會是奇數與偶數相加」，你都缺乏直接的推論過程證明其為真。（我想你大概是「我觀察到的現象就是這樣子阿」，這在數學領域是行不通的，數學領域多的是觀察結果不可靠的 case）

你的第二段的後半段，我幫你拼接起來：「若 d 為奇數，當 n 為奇數時，(a1+an) 會是奇數相加或奇數與偶數相加，所以 (a1+an) * n 必為偶數。」

* 為什麼 a1 + an 會是：「兩個 odd 相加」或是「odd + even」（基本上就是我這個 comment 第一段在 blame 的部份）
* 就算我不管上面一句是怎麼來的，直接承認他是對的，(odd + even) * odd 會是偶數？（你還強調「必然」咧....）

**Comment by SayHello123** [comment]
用於數學領域的直接的推論過程應該是長怎樣的呢？

第二段修正：
若 d 為奇數，當 n 為偶數時，`(a1+an)` 會是奇數與偶數相加，因 a1 與 an 之間的 d 的數量會為奇數（`an = a1 + (n-1)d` ），所以當 a1 為奇數時，an 就會為偶數；當 n 為奇數時，`(a1+an)` 會是奇數相加或偶數相加，因 an 與 an 之間的 d 的數量為偶數（`an = a1 + (n-1)d` ），所以當 a1 為奇數時，an 就會為奇數，而其相加結果都會是偶數。
因此當 d 為奇數時， `(a1+an) * n`  必為偶數。

**Comment by MontyPan** [comment]
我最後再講一次：

* 你要交的是一個完整的證明，而不是縫縫補補的東西
* 你在寫「若 A 則 B / 若 A 則必為 B」的時候，都要給推導過程。你自己數數看你寫了多少個「必為 xxx」而看不出任何憑據。

---------

就算我容忍你只修正第二段

* 你花了一堆字說明「若 d 為奇數，當 n 為偶數時，(a1+an) 會是奇數與偶數相加」，然後咧？
    * 數學推論裡頭不喜歡看到倒裝句型。
    * 那 a1 是偶數的情況咧？
        * 當 n 是 odd 的部份也有一樣的問題。
    * a1 + an 是 odd + even，結果會是 odd。那這跟你後頭的論述有什麼關係？


---------

最後，對，簡單地來說，你之前的證明過程完全沒有提到 an = a1 + (n-1) * d，所以我們可以懷疑你說的「a1 + an 是 xxx」的論述不一定正確。

然後，反過來說，如果你都知道 an = a1 + (n - 1) * d 也拿來用了，那你的證明就不應該那麼繁瑣，以至於讓人有一堆東西可以懷疑。（簡化到最後就會變成我說的「a1 是 odd 還是 even 根本不重要」）（你目前的推論方式無法，你還是必須檢視 a1 是 odd 還是 even）。

--------

我給你一個完全不用討論 odd / even 的證明方式，並盡我所能地寫的很數學：

```
當 n = 1 時，Sn = a1，（根據前提假設，a1 是整數，其實這可以不用寫）所以 Sn 是整數。
假設 n = x 時，Sx 是整數。
則 n = x + 1 = y（y 是為了方便電腦上書寫）時，
Sy = Sx + ay = Sx + (a1 + (x + 1 -1) * d) = Sx + a1 + x * d
由於 Sx , a1, x, d 都是整數，根據整數乘法與加法封閉性，可得之 Sy 是整數。
根據數學歸納法，Sn 必為整數。
```

當然，如果你夠龜毛的話，你可以挑毛病說：阿你也沒有證明「數學歸納法」、「整數乘法封閉性」那些鬼阿幹....

這個部份就真的很數學了，我不太確定「整數乘法封閉性」算不算公設 / 公理，如果是的話就不用證（想證明也沒辦法）.... 如此之類的....

一個簡單但是實際上數學家（應該）也是這麼檢視的方法是：只要你引用的東西（B）、不需要透過你要證明的東西（A）來證明，就可以拿來用。

白話文的舉例：「你怎麼知道 A 不是騙子？」「因為 B 擔保」「那你怎麼知道 B 不是騙子」「因為 A 擔保」。

**Comment by SayHello123** [comment]
若 d 為偶數，a1 會影響 an 為奇數還是偶數，當 a1 為奇數時 ，所以 `(a1+an)` 只會是奇數相加或是偶數相加，而其相加結果都會是偶數，所以 `(a1+an) * n` 必為偶數。
2, 4, 6
2, 4
1, 3 5
1, 3
若 d 為奇數，當 n 為偶數時，因 a1 與 an 之間的 d 的數量會為奇數（an = a1 + (n-1)d ），所以當 a1 為奇數時，an 就會為偶數，所以 (a1+an) 會是奇數與偶數相加；當 n 為奇數時，因 an 與 an 之間的 d 的數量為偶數（an = a1 + (n-1)d ），所以當 a1 為奇數時，an 就會為奇數，所以 (a1+an) 會是奇數相加或偶數相加，。
因此當 d 為奇數時， (a1+an) * n 必為偶數。

因此當 a1、d、n 都為整數（且 n 大於 1）時，`(a1 + an) * n / 2` 就必為整數。

**Comment by SayHello123** [comment]
若 d 為偶數，無論 n 為奇數或偶數，都是由 a1 影響 an 為奇數還是偶數，當 a1 為奇數時，an 就會是奇數，而當 a1 為偶數時，an 就會是偶數，所以 `(a1+an)` 只會是奇數相加或是偶數相加，而其相加結果都會是偶數。
因此當 d 為偶數時，`(a1+an) * n` 必為偶數。

若 d 為奇數：
當 n 為偶數時，因 a1 與 an 之間的 d 的數量會為奇數（an = a1 + (n-1)d ），所以當 a1 為奇數時，an 就會為偶數，而當 a1 為偶數時，an 就會為奇數，所以 `(a1+an)` 會是奇數與偶數相加；但因 n 為偶數，所以 `(a1+an) * n` 必為偶數。

當 n 為奇數時，因 a1 與 an 之間的 d 的數量為偶數（an = a1 + (n-1)d ），所以當 a1 為奇數時，an 就會為奇數，而當 a1 為偶數時，an 就會是偶數，所以 `(a1+an)` 會是奇數相加或偶數相加，而其相加結果都會是偶數。
因此 `(a1+an) * n` 必為偶數。
因此當 d 為奇數時， `(a1+an) * n` 必為偶數。

因此當 a1、d、n 都為整數（且 n 大於 1）時，`(a1 + an) * n / 2` 就必為整數。

-----------------------------------

用數學的證明方式真的好難，我連看你寫出來的算式都看不太懂囧

**Comment by MontyPan** [comment]
唉... 你這就是典型「靠工人智慧解決問題」，對是對了（應該，我實在沒耐心仔細看了），但是有件事情是亙古不便的：「寫越多，有錯的機率就越大」。

重點是，有些事情你自己也知道了，為什麼不徹底利用呢？例如第二段的最後「但因 n 為偶數，所以 (a1+an) * n 必為偶數」，一開始就來這麼一刀不就能砍掉一堆問題了？然後搭配一下基本的排列組合用條列的方法來確保 **窮舉**（對，你之前有 n 次都犯了這個毛病，你這種證明路線就是要確保窮舉）

```
Sn = (a1 + an) * n / 2  
若 n 是 even，則 Sn 必為整數  
若 n 是 odd，則 (a1, d) 的奇、偶數組合有下列可能：

* (odd, odd) ：blahblah
* (even, odd) ： blahblah
* (odd, even) ： blahblah
* (even, even) ： 同 (odd, even)。
```

這樣你是不是就不容易漏掉 case，看的人再怎麼懶惰也至少能馬上確認你有窮舉？

再進一步說，你都知道 an = a1 + (n - 1) * d（順便 murmur，我不建議在電腦書寫的時候把乘號省略，不然 a1 / an 會變得很詭異），你也知道 Sn = (a1 + an) * n / 2，那你為什麼不兩個摻在一起 ~~做撒尿牛丸~~ 整理一下？

```
a1 + an =  a1 + a1 + (n - 1) * d = 2 * a1 + (n - 1) * d
```

對你來講，可能到這邊就是極限了（拜託不要 😱 ），但是即便這樣也能讓你的證明過程輕鬆很多，因為 2 * a1 一定是 even，所以 (n - 1) * d 如果是 odd、a1 + an 就會是 odd，反之亦然。

所以你要檢視的東西就從 a1, n, d 三個參數，變成 n, d 兩個參數。（這就是我說的 a1 是 odd / even 根本不重要）

然後，對真正的目標（Sn），n 是 even 直接結案，所以只需要考慮 n 是 odd，然後你會發現 d 是 odd 還是 even 也一點也不重要了。因為 n 是 odd 的話，n - 1 一定是偶數。結案。

當然我這邊是用口語敘述的方式（為了引導你.... 😭 ），得重頭修飾一下才能寫成數學的論述方式。

真正要化簡的話（aka 我用你的路線證明的話），會是這樣的

```
(a1 + an) * n = 2 * a1 * n + n^2 * d - n * d = 2 * a1 * n + n * (n - 1) * d  
（如果上面那行不知道發生什麼事情，請找個理工組的人請他教你）  
（如果理工組的不會，為了國家的未來，請直接殺了他就地掩埋 [完全誤]）  
2 * a1 * n 必為偶數、而 n 與 n -1 其中必有一個是偶數，所以 n * (n - 1) * d 也必為偶數  
所以 (a1 + an) * n 必為偶數  
則 Sn = (a1 + an) * n / 2 必為整數  
```

當然，還是沒有數學歸納法來的簡單。

------------

搞這一輪，除了確認 / 訓練你的數學程度之外 ~~（謎之聲：我怎麼知道會近似於零）~~ ，也是要再次提醒你「數學很重要」這檔事情。

正常的理工組，高中跟大學的數學訓練可能差不多（87%）就能應付一般程式設計師需要的數學，搞演算法或是圖學之類的就再說。但是呢... 你可能基本代數運算都...... [扶額]

請注意，數學的重點不在於計算有多厲害，而是在於處理問題的方法。

換個方式講，假設今天你的證明跟我的證明要寫成程式讓電腦跑，誰會寫的比較快？

大概就是這麼回事情。
