### ISSUE TITLE
怎麼加都一樣的方陣

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Sara#16]
「方陣」是一種特殊的「矩陣」，用數學語言講是「n * n 的矩陣」，用白話文講是「row 跟 column 個數一樣的矩陣」。

至於矩陣是什麼... 我是不敢要你去看 wikipedia，那實在太可怕，用最凡人的詞彙大概就是 excel 裡頭的格子填入一堆數字這樣...... 🙊 

這裡給一個 n = 3 的方陣做例子（正式寫法，左右還會加上中括號，這裡就原諒我懶得補了）：

```
1 2 3
5 5 5
6 3 0
```

至於我們要搞的不單只是方陣而已，完整的需求是「n 為奇數、而且裡頭填入 1～n^2 的整數，並且無論直、橫、斜線加起來的數字都要相等」

一樣舉 n = 3 的例子

```
8 1 6
3 5 7
4 9 2
```

在這個 case 當中，你會發現無論直、橫、斜這 8 條線的數字加起來都是 15。

-----------------------------------------------

好的，你要做的事情呢，就是寫一個解法（基本上不太可能想得出來 XD） or 提示，讓你手下的小弟們可以比較順利地產生出符合條件的矩陣。

至於什麼是「提示」，我舉拼圖的例子好了：

1. 先找出邊框的板塊
2. 把邊框拼出來
3. 用顏色把剩下的板塊分類

雖然最終還是逃不過一片一片拿起來試試看的命運，不過有了上面的提示肯定可以拼的比較快（相對於一開始就矇著頭試試看）。

如果太難，你可以只處理 n = 3 的狀況...... 🙈 

--------------------------------------------

### 雜談 ###
* 對，這其實有公式解（所以可以寫成程式），我真心無法理解找出公式解的神 ~~經病~~ 腦袋是怎麼想的、也不知道這玩意要怎麼證明...... 
* 你還是可以看一下矩陣的 wikipedia，上頭炸了一個很有趣的翻譯問題。對岸的 row / column 翻法剛好跟我們相反...... 所以... 還是都講原文吧....... 😱

**Comment by SayHello123** [comment]
|n=3|||
|--|--|--|
| 8 | 1 | 6 |
| 3 | 5 | 7 |
| 4 | 9 | 2 |

|奇偶分類|||
|--|--|--|
| 偶 | 奇 | 偶 |
| 奇 | 奇 | 奇 |
| 偶 | 奇 | 偶 |

|a=5|||
|--|--|--|
| a+3 | a-4 | a+1 |
| a-2 | a | a+2 |
| a-1 | a+4 | a-3 |

|顏色分類|||
|--|--|--|
| 紅 | 綠 | 黃 |
| 藍 | 白 | 藍 |
| 黃 | 綠 | 紅 |

推論結論：

以中間的數字為中心點的左右兩邊（斜、橫、直）相加後除以二的值會等於中間的數字，顏色分類同顏色為一組。

**Comment by MontyPan** [comment]
＝＝" 你不覺得這樣的敘述很... 囉唆又不直接嗎？

你要說的應該是：在 n = 3 的前提下，正中間的格子給 1～9 的中位數 5，然後剩下的數字分成 4 組，每一組的數字為 (5 + x, 5 - x)，其中 1 <= x <= 4。每一組數字分佈在以 5 為中心對應兩側的格子內。

謎之聲：X 你 X 的這樣有比較直接跟不囉唆？ [飛踢]

答案是有的，原因就是後頭問題的提示（謎之聲：WHAT THE FUCK 啦，又來這個？）

---------------------------------

# Must Answer #

* 其實你這樣講，還少了一些東西才能完成 n = 3 的矩陣吧？那缺了什麼？有辦法寫成提示嗎？
* 以整個問題來說，你這個思路會遇到什麼問題？

**Comment by SayHello123** [comment]
方陣邊界為 n * n，此例 n = 3
總區塊數為 3 * 3 = 9 格 => 1, 2, 3, 4, 5, 6, 7, 8, 9
找到中心數字 x 為 (a1 + an) / 2 = (a2 +an-1) /2 = (a3 + an-2) / 2 = (a4 + an-3) /2
換言之，總共組數為 9 / 2 = 4 組 .....1中心數字


______________________________________________________________________


- 列出以上後還是想不到缺了甚麼（汗）
- 若 n 為偶數就不適用這個思路

**Comment by MontyPan** [comment]
> 找到中心數字 x 為 (a1 + an) / 2 = (a2 +an-1) /2 = (a3 + an-2) / 2 = (a4 + an-3) /2

完全不知道你在寫三小....

> 若 n 為偶數就不適用這個思路

老闆請不要修改已知... 一開頭就寫了：

> 完整的需求是「n 為 **奇數**、而且裡頭填入 1～n^2 的整數，並且無論直、橫、斜線加起來的數字都要相等」

**Comment by SayHello123** [comment]
只要能找出中心數字，就能完成 n = 3 的方陣
而找出中心數字的方法就是總格數除以 2 後，第（商數 + 餘數）的位數為中心數字
（在這邊是9 / 2 = 4 ，餘數為 1，而 4 + 1 = 5，中心數字為第 5 個數字，即是 5）

**Comment by MontyPan** [comment]
＝＝" 我開始懷疑你用 comment 海戰術來敷衍我了....

> 只要能找出中心數字，就能完成 n = 3 的方陣

只要把地球上每一寸地都鑽洞，就能發現石油...... 你不覺得這是完全沒有用的話嗎？那還不如直接說「阿你就 try 完所有排列組合（不多，也才 362880 組，如果考慮 rotation 之後等價之類的哏會更少）就能完成 n = 3 的方陣」

> 而找出中心數字的方法就是總格數除以 2 後，第（商數 + 餘數）的位數為中心數字

後面就更不知道在回答三小.... 找出中位數這件事情壓根不是問題阿...

（因為 **前提假設** 規定，填入方陣的是 1～n^2 的連續整數，所以中心數字就是中位數也是平均數就是 (1 + n^2) / 2)） ~~（要不要再來證明一下奇數偶數）~~

--------------------

請回到 https://github.com/MontyPan/T-Sara/issues/16#issuecomment-687838315 ，你要回答的是「還少了什麼」，而不是一直 repeat 你一開始就講過的東西。

甚至我看不懂的東西如果跟回答問題沒直接關係，你也可以跳過不理.... Zzzz

**Comment by SayHello123** [comment]
> # Must Answer
> * 其實你這樣講，還少了一些東西才能完成 n = 3 的矩陣吧？那缺了什麼？有辦法寫成提示嗎？
> * 以整個問題來說，你這個思路會遇到什麼問題？

真的想不到了 QQ 可以提供其他提示嗎？

**Comment by MontyPan** [comment]
因為 #36 處於一個混戰的狀態，而且是一個「有良心的人就不好意思設 deadline」的狀態（對啦，我有良心，你有意見嗎？ 😡 ），所以另外開一個純 coding 的 task。

是的，請把這個方陣寫出來 & 印出來。

1. 使用者可以決定 n 的大小（一樣，可以不用防呆，包含檢查是不是奇數）
2. 你不用抽 class（ #37 已經夠慘了），全部都寫在 `sara.basic.issue16.Main` 裡頭就好
3. 你 **只能用一維陣列**，不能用二維陣列、也不能用其他 class / object

假設座標系的原點在左上角，第一個格子是 (1, 1)，方陣的建立方法是：

1. 1 是放在 (n/2, 1) 的位置， n/2 無條件進位到整數（就是中間啦）
2. 假設 a > 1，且 a-1 的位置是 (x, y)，那麼 a 的位置就會是 (x+1, y-1)
    1. 如果超出邊界就跳到另外一邊去（迴圈邊界的概念）
    2. 如果那個位置已經有填入數字了，那麼就改放在 (x, y+1)

以 n = 3 舉例：

1. (2, 1)
2. (3, 3)：y 超出邊界，所以要套 2.1
3. (1, 2)：x 超出邊界，所以要套 2.1
4. (1, 3)：(2, 1) 已經有數字了，所以要套 2.2
5. (2, 2)
6. (3, 1)
7. (3, 2)：x, y 都超出邊界，套 2.1 的結果是 (1, 3)，但是那個位置也有數字了，所以要改套 2.2


```
   1   2   3  (x)
 1 ８｜１｜６
   －＋－＋－
 2 ３｜５｜７
   －＋－＋－
 3 ４｜９｜２
(y)


17|24| 1| 8|15
--+--+--+--+--
23| 5| 7|14|16
--+--+--+--+--
 4| 6|13|20|22
--+--+--+--+--
10|12|19|21| 3
--+--+--+--+--
11|18|25| 2| 9

```

**Comment by MontyPan** [comment]
忘記寫了，因為事關重大所以獨立一個 comment。

你必須在 2021/1/17 23:59 前交出至少執行正確的版本。

喔對， #37 也不能沒進度。
