### ISSUE TITLE
Java 開發環境建置

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Sara#2]
# JDK #

https://www.oracle.com/java/technologies/javase-downloads.html

基本上下載 v14 或是 v8 都行 ~~（如果你對 GWT 很有興趣的話那就下載 v8 XD）~~，然後安裝... (ry

# IDE（Eclipse） #

**注意：不是非用 Eclipse 不可（甚至不用 IDE 也行），但是我只有用過 Eclipse、也只會提供 Eclipse 的步驟 & 障礙排除**

https://www.eclipse.org/downloads/packages/

基本上下載「Eclipse IDE for Java Developers」就可以了，下載之後解壓縮會得到一個 eclipse 的目錄、移到乾淨（？）的目錄，然後執行 eclipse.exe 

## import project ##
1. git clone T-Sara 到 local，假設目錄是 `W:\git\T-Sara`
    * 如果你還沒 fork，先 fork 然後 clone 你自己的 remote repo 會省事一點
    * 如果之前就 clone 過，那就做 `git pull -r`
1. （回到 Eclipse 裡頭）上方 menu bar 的 File→Import
1. 中間樹狀區找 Maven→Existing Maven Project，按下 next
1. Root Directory 的輸入框輸入 `W:\git\T-Sara`，下方 `Projects` 會出現一個 item 跟 checkbox（可以勾選的正方形），勾選之後按下 finish
1. 上方 menu bar 的 Window→Show View→Project Explorer
    * 他可能本來就在畫面上的某一個區域（Eclipse 稱之為 view），如果你選了畫面沒反應，那應該就是原本就已經打開了，請自己找一找吧，看起來跟檔案總管差不多。
1. Project Explorer 裡頭會出現一個「sara」，在裡頭找到一個「HelloWorld.java」，對他按下右鍵選擇「Run As...」→「Java Application」
1. （應該）會跑出一個「Console」的 view，裡頭出現「Hello World」，那麼就大功告成了，請在這個 issue 下方留 comment 表示完成，這樣我就可以開始出題目啦 :woman_dancing: 

------------------------------------------------------------

# 注意 #
* 如果你遇到什麼問題，請儘快 call help
* 我還在用有點舊的 Eclipse，也許有些部份已經改掉、不是我敘述的那樣樣子，如果你沒辦法自行轉換，請儘快 call help

**Comment by SayHello123** [comment]
設置完成
