### ISSUE TITLE
為什麼 Excel 會爆炸呢？

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Sara#26]
這是起源於 https://dq.yam.com/post.php?id=13062 這個.... 新聞？在脈絡上是 #1 跟 #3 的綜合性延伸題。請依序回答下列問題：

* Java primitive data type 的 byte / short / int 的值域為何？（不懂值域... 請自己狗... 還是不懂請在下方蓋大樓問）
* 上述的 data type 值域範圍是怎麼界定（好啦，其實就是計算）出來的？
* 請解釋為什麼新聞當中 Excel 的資料筆數的範圍是 65536 / 1048576
    * 坦白說 65536 很常見，1048576 就... 很冷門，我知道怎麼算出來但是不知道為啥是這個數字....

**Comment by SayHello123** [comment]
byte 的值域為：-128~127

short 的值域為：-32768~32767

int 的值域為：-2147483648~2147483647

______________________________________________________________________

byte 的值域範圍計算：-2^7 ~ 2^7 -1
short 的值域範圍計算：-2^15 ~ 2^15 -1
int 的值域範圍計算：-2^31 ~ 2^31-1

______________________________________________________________________

65,535 = 2^16
Excel 97 ~ 2003 的工作表資料官方限制為：65,536 rows x 256 columns

Reference : [Excel 與舊版 Excel 搭配使用](https://support.microsoft.com/zh-tw/office/excel-%e8%88%87%e8%88%8a%e7%89%88-excel-%e6%90%ad%e9%85%8d%e4%bd%bf%e7%94%a8-2fd9ffcb-6fce-485b-85af-fecfd651a5ac?ocmsassetid=ha010342994&correlationid=6ad633e7-6a27-46c7-9c68-b8269f019b80&ui=zh-tw&rs=zh-tw&ad=tw)
